modera_languages:
    - { locale: en }
    - { locale: ru }
    - { locale: et }

modera_file_uploader:
    is_enabled: true
    url: /backend/uploader-gateway

modera_server_crud:
    exception_handler: modera_server_crud.exception_handling.bypass_handler

modera_mjr_integration:
    extjs_path: "/extjs"
    runtime_path: "/modera/mjr"
    viewport_class: "MF.theme.authenticationaware.Viewport"
    main_config_provider: "modera_dynamically_configurable_mjr.mjr.main_config"

modera_mjr_theme_integration:
    theme_path: "/modera/theme"

modera_mjr_security_integration:
    login_url: _security_check
    logout_url: _security_logout
    is_authenticated_url: modera_mjr_security_integration.index.is_authenticated
