root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path:   /backend
        permanent: true

_modera_routing:
    resource: "@ModeraRoutingBundle/Resources/config/routing.yml"
